import ToolPageLayout from '../../components/ToolPageLayout';
import YouTubeCreatorKit from '../../components/YouTubeCreatorKit';
import FaqSection from '../../components/FaqSection';
import { SITE_URL, TOOL_PAGES } from '../../lib/siteConfig';

const page = TOOL_PAGES.youtubeCreatorKit;

export const metadata = {
  title: page.title,
  description: page.description,
  keywords: page.keywords,
  alternates: { canonical: `/${page.slug}` },
  openGraph: {
    title: page.title,
    description: page.description,
    url: `${SITE_URL}/${page.slug}`,
  },
  twitter: {
    title: page.title,
    description: page.description,
  },
};

export default function Page() {
  return (
    <ToolPageLayout
      eyebrow="FREE · NO LOGIN · RUNS IN YOUR BROWSER"
      title="YouTube Creator Kit"
      subtitle="Generate high-retention hooks and A/B test your thumbnail before you upload — free."
      seoContent={
        <FaqSection
          heading="Free YouTube hook generator & thumbnail tester — how it works"
          intro={[
            'The Hook Generator turns any topic into 5 psychology-backed opening lines — formulas like The Negative Frame, The Curiosity Gap, and The Contrarian Take, each labeled with the psychological trigger it uses, so you can pick the one that fits your video instead of guessing. The A/B Thumbnail & Title Previewer renders two thumbnails side-by-side inside a realistic YouTube feed card — with your title, a channel avatar placeholder, mock view counts, and a light/dark mode toggle — so you can see which one actually stands out before you publish.',
          ]}
          items={[
            {
              q: 'Are the hooks generated by an AI model?',
              a: 'No — they come from a library of 12 proven hook formulas with topic-substitution logic, so results are instant, free, and never rate-limited.',
            },
            {
              q: 'Are the view counts and channel name on the thumbnail preview real?',
              a: 'No — they\'re illustrative mock data styled to match a real YouTube card, purely so you can judge how your thumbnail and title look in context.',
            },
            {
              q: 'Do my thumbnail images get uploaded anywhere?',
              a: 'No. Thumbnails are read locally in your browser and never leave your device.',
            },
          ]}
        />
      }
    >
      <YouTubeCreatorKit />
    </ToolPageLayout>
  );
}
